CREATE TYPE "ICPQualificationPolicy" AS ENUM ('CONSERVATIVE', 'BALANCED', 'STRICT');
CREATE TYPE "LeadSourceType" AS ENUM ('UNKNOWN', 'USER_CURATED', 'BROAD_POOL', 'FRAMELEADS_QUALIFIED');
CREATE TYPE "QualificationReasonCode" AS ENUM ('NONE', 'EXCLUDED', 'TARGET_MISMATCH', 'MISSING_DATA', 'AMBIGUOUS', 'NO_RULES', 'INACTIVE', 'USER_OVERRIDE');
CREATE TYPE "QualificationOverride" AS ENUM ('AUTO', 'USER_QUALIFIED', 'USER_EXCLUDED');

ALTER TABLE "ICPProfile" ADD COLUMN "qualificationPolicy" "ICPQualificationPolicy" NOT NULL DEFAULT 'CONSERVATIVE';
ALTER TABLE "LeadList" ADD COLUMN "sourceType" "LeadSourceType" NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE "ProspectQualification"
  ADD COLUMN "reasonCode" "QualificationReasonCode" NOT NULL DEFAULT 'NONE',
  ADD COLUMN "policyVersion" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "override" "QualificationOverride" NOT NULL DEFAULT 'AUTO',
  ADD COLUMN "overriddenAt" TIMESTAMP(3);
